apiVersion: v1
kind: Template
metadata:
  name: osb-starter-pack
objects:

- apiVersion: servicecatalog.k8s.io/v1beta1
  kind: ClusterServiceBroker
  metadata:
    name: osb-starter-pack
  spec:
    url: https://osb-starter-pack.osb-starter-pack.svc.cluster.local
    caBundle: ${BROKER_CA_CERT}
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: osb-starter-pack

- kind: Service
  apiVersion: v1
  metadata:
    name: osb-starter-pack
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: 'osb-starter-pack-ssl'
    labels:
      app: osb-starter-pack
  spec:
    selector:
      app: osb-starter-pack
    ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: osb-starter-pack
    labels:
      app: osb-starter-pack
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: osb-starter-pack
    template:
      metadata:
        labels:
          app: osb-starter-pack
      spec:
        containers:
        - name: service-osb-starter-pack
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          command:
          - /opt/servicebroker/servicebroker
          args:
          - --port
          - "8443"
          - -v
          - "4"
          - --logtostderr
          - --tls-cert-file
          - "/var/run/osb-starter-pack/starterpack.crt"
          - --tls-private-key-file
          - "/var/run/osb-starter-pack/starterpack.key"
          ports:
          - containerPort: 8443
          readinessProbe:
            tcpSocket:
              port: 8443
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 8443
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          volumeMounts:
          - mountPath: /var/run/osb-starter-pack
            name: osb-starter-pack-ssl
            readOnly: true
        volumes:
        - name: osb-starter-pack-ssl
          secret:
            defaultMode: 420
            secretName: osb-starter-pack-ssl
            items:
            - key: tls.crt
              path: starterpack.crt
            - key: tls.key
              path: starterpack.key

parameters:
- description: Name of the image to use
  displayName: Image name
  name: IMAGE
  required: true
  value: quay.io/osb-starter-pack/servicebroker:latest

- description: base64 encoded SSL CA Certificate
  displayName: base64 encoded SSL CA Certificate
  name: BROKER_CA_CERT
  required: true
  value: 
